name: golangci-lint
version: 1.58.2
summary: Fast linters runner for Go
description: |
  Runs linters in parallel, uses caching, supports yaml config, has
  integrations with all major IDE and has dozens of linters included.

base: core22
confinement: classic
grade: stable

apps:
  golangci-lint:
    command: bin/golangci-lint

parts:
  golangci-lint:
    plugin: go
    source: https://github.com/golangci/golangci-lint.git
    source-tag: v$SNAPCRAFT_PROJECT_VERSION
    build-packages:
      - git
      - gcc
    build-snaps:
      - go/latest/stable
    override-build: |
      sed -i s/'"master"'/'"'"$SNAPCRAFT_PROJECT_VERSION"'"'/ cmd/golangci-lint/main.go
      sed -i s/'"?"'/'"'$(git rev-parse --short HEAD)'"'/ cmd/golangci-lint/main.go
      sed -i s/'""'/'"'$(date -u +%Y-%m-%dT%TZ)'"'/ cmd/golangci-lint/main.go
      craftctl default
