name: golangci-lint
summary: Fast linters runner for Go
description: |
  Runs linters in parallel, uses caching, supports yaml config, has
  integrations with all major IDE and has dozens of linters included.
version: 1.41.1

base: core18
confinement: strict

apps:
  golangci-lint:
    command: golangci-lint
    plugs:
      - home
      - network

parts:
  golangci-lint:
    plugin: fetch-golangci-lint
    version: $SNAPCRAFT_PROJECT_VERSION
    stage:
      - golangci-lint

  # golangci-lint requires a go binary in $PATH so use the go snap for this
  go:
    plugin: nil
    stage-snaps:
      - go
    stage-packages:
      - libc6

